import { Inter, League_Spartan, Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const inter = Poppins({ weight:['400','800'] ,subsets: ["latin"] });
const la = League_Spartan({ weight:['400','800'] ,subsets:["latin"]})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='dark'>
      <body>
        
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
